In [94]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
import os
import re
import numpy as np
import zipfile
import tempfile
import json

Сбор данных в один DataFrame

In [17]:
zip_path = "C:\\Users\\79511\\Desktop\\places\\data.zip"

In [20]:
def load_all_csv(zip_path):
    with tempfile.TemporaryDirectory() as temp_dir:  # Временная папка для распаковки
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(temp_dir)  # Распаковываем ZIP
        directory = temp_dir  # Путь к распакованным файлам
        
        dfs = []
        for root, dirs, files in os.walk(directory):  # Рекурсивный обход всех подпапок (например, 'data')
            for filename in files:
                if filename.endswith('.json'):  # Ищем .json с CSV-содержимым
                    filepath = os.path.join(root, filename)
                    try:
                        df = pd.read_csv(filepath, low_memory=False)  # Читаем как CSV
                        df['original_file'] = filename  # Отслеживаем источник (кафе, парки и т.д.)
                        dfs.append(df)
                    except pd.errors.ParserError:
                        print(f"Ошибка парсинга файла {filename} — проверьте формат (возможно, не CSV внутри).")
        if not dfs:
            raise ValueError("Нет файлов для объединения — проверьте содержимое ZIP (ожидаются .json с CSV-структурой в папках).")
        combined_df = pd.concat(dfs, ignore_index=True)
        print(f"Объединено {len(dfs)} файлов, всего строк: {len(combined_df)}")
    return combined_df  # Временная директория удалится автоматически

In [34]:
df = load_all_csv(zip_path)

Объединено 18 файлов, всего строк: 3597

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3597 entries, 0 to 3596
Data columns (total 34 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   input_id               3597 non-null   object
 1   link                   3597 non-null   object
 2   title                  3597 non-null   object
 3   category               3589 non-null   object
 4   address                3591 non-null   object
 5   open_hours             3597 non-null   object
 6   popular_times          3597 non-null   object
 7   website                2425 non-null   object
 8   phone                  2970 non-null   object
 9   plus_code              3578 non-null   object
 10  review_count           3597 non-null   int64
 11  review_rating          3597 non-null   float64
 12  reviews_per_rating     3597 non-null   object
 13  latitude               3597 non-null   float64
 14  longitude              3597 non-null   float64
 15  cid                    3597 non-null   uint64
 16  status                 2817 non-null   object
 17  descriptions           402 non-null    object
 18  reviews_link           3451 non-null   object
 19  thumbnail              3525 non-null   object
 20  timezone               3597 non-null   object
 21  price_range            622 non-null    object
 22  data_id                3597 non-null   object
 23  images                 3597 non-null   object
 24  reservations           212 non-null    object
 25  order_online           350 non-null    object
 26  menu                   3597 non-null   object
 27  owner                  3597 non-null   object
 28  complete_address       3597 non-null   object
 29  about                  3270 non-null   object
 30  user_reviews           3597 non-null   object
 31  user_reviews_extended  2957 non-null   object
 32  emails                 0 non-null      float64
 33  original_file          3597 non-null   object
dtypes: float64(4), int64(1), object(28), uint64(1)
memory usage: 955.6+ KB

In [40]:
df.head()

,input_id,link,title,category,address,open_hours,popular_times,website,phone,plus_code,review_count,review_rating,reviews_per_rating,latitude,longitude,cid,status,descriptions,reviews_link,thumbnail,timezone,price_range,data_id,images,reservations,order_online,menu,owner,complete_address,about,user_reviews,user_reviews_extended,emails,original_file,unique_key
0,837aed36-07fb-4804-85b2-be8e0285a3b1,https://www.google.com/maps/place/Flying+Squir...,Flying Squirrel Trampoline Park,Recreation center,"231 Warbonnet Dr, Moscow, ID 83843","{""Friday"":[""12–7 PM""],""Monday"":[""12–7 PM""],""Sa...","{""Friday"":{""10"":0,""11"":0,""12"":47,""13"":56,""14"":...",https://flyingsquirrelsports.us/moscow-idaho/,(208) 596-4043,"PXM6+XV Moscow, Idaho",124,4.3,"{""1"":8,""2"":4,""3"":8,""4"":28,""5"":76}",46.734966,-117.037819,13690396177102462202,Closed ⋅ Opens 12 PM,NaN,https://search.google.com/local/reviews?placei...,https://lh3.googleusercontent.com/p/AF1QipPsfv...,America/Los_Angeles,NaN,0x549f896fa42645db:0xbdfe0ec9ca8edcfa,"[{""title"":""All"",""image"":""https://lh3.googleuse...",NaN,NaN,"{""link"":"""",""source"":""""}","{""id"":""102302584020440887707"",""name"":""Flying S...","{""borough"":"""",""street"":""231 Warbonnet Dr"",""cit...","[{""id"":""accessibility"",""name"":""Accessibility"",...",[],"[{""Name"":""Jordan Lott"",""ProfilePicture"":""https...",NaN,amusement_parks_trampoline_centers.json,flying squirrel trampoline park_231 warbonnet ...
1,837aed36-07fb-4804-85b2-be8e0285a3b1,https://www.google.com/maps/place/Joki+Joya/da...,Joki Joya,Amusement park,"Porechnaya Ulitsa, 10, Moscow, Russia, 109469","{""Friday"":[""10 AM–10 PM""],""Monday"":[""10 AM–10 ...","{""Friday"":{""10"":33,""11"":42,""12"":49,""13"":55,""14...",http://joki-joya.ru/birthday/?utm_campaign=ant...,+7 495 162-53-50,"MQ2C+36 Maryino District, Moscow, Russia",1796,4.7,"{""1"":47,""2"":21,""3"":63,""4"":199,""5"":1466}",55.650147,37.770601,5739208106037163393,Closes soon ⋅ 10 PM ⋅ Opens 10 AM Wed,NaN,https://search.google.com/local/reviews?placei...,https://lh3.googleusercontent.com/p/AF1QipMyNz...,Europe/Moscow,NaN,0x414ab41d4148b01d:0x4fa5c35d64633581,"[{""title"":""All"",""image"":""https://lh3.googleuse...",NaN,NaN,"{""link"":"""",""source"":""""}","{""id"":""118056095202336741127"",""name"":""Joki Joy...","{""borough"":""South-Eastern Administrative Distr...","[{""id"":""accessibility"",""name"":""Accessibility"",...",[],"[{""Name"":""Андрей Донич"",""ProfilePicture"":""http...",NaN,amusement_parks_trampoline_centers.json,"joki joya_porechnaya ulitsa, 10, moscow, russi..."
2,837aed36-07fb-4804-85b2-be8e0285a3b1,https://www.google.com/maps/place/Sportivno-Ra...,Sportivno-Razvlekatel'nyy Tsentr Nebo,Amusement center,"Yeniseyskaya Ulitsa, 36с1, Moscow, Russia, 129281",{},{},http://nebojump.ru/,+7 495 172-11-32,"VMG9+9M Babushkinsky District, Moscow, Russia",1167,4.6,"{""1"":44,""2"":19,""3"":44,""4"":136,""5"":924}",55.875978,37.669142,12009132956795049123,NaN,NaN,https://search.google.com/local/reviews?placei...,https://lh3.googleusercontent.com/p/AF1QipP9Zq...,Europe/Moscow,NaN,0x46b536cb9aea4ea3:0xa6a902cc0e3494a3,"[{""title"":""All"",""image"":""https://lh3.googleuse...",NaN,NaN,"{""link"":"""",""source"":""""}","{""id"":""110370684845941323728"",""name"":""Sportivn...","{""borough"":""North-Eastern Administrative Okrug...","[{""id"":""accessibility"",""name"":""Accessibility"",...",[],"[{""Name"":""Александр Доев"",""ProfilePicture"":""ht...",NaN,amusement_parks_trampoline_centers.json,sportivno-razvlekatel'nyy tsentr nebo_yeniseys...
3,837aed36-07fb-4804-85b2-be8e0285a3b1,https://www.google.com/maps/place/Park+%22Luko...,"Park ""Lukomor'ye""",Theme park,"Poselok Sovkhoz Imeni Lenina, 7а, Sovkhoza Im....","{""Friday"":[""9 AM–9 PM""],""Monday"":[""9 AM–9 PM""]...","{""Friday"":{""10"":20,""11"":27,""12"":34,""13"":39,""14...",NaN,NaN,"HPMP+F2 Sovkhoza Im. Lenina, Moscow Oblast, Ru...",6030,4.9,"{""1"":73,""2"":32,""3"":89,""4"":262,""5"":5574}",55.583665,37.735077,13371007728590602425,Closed ⋅ Opens 9 AM Wed,NaN,https://search.google.com/local/reviews?placei...,https://lh3.googleusercontent.com/gps-cs-s/AC9...,Europe/Moscow,NaN,0x414ab1a514dd6cb5:0xb98f5cafbfa540b9,"[{""title"":""All"",""image"":""https://lh3.googleuse...",NaN,NaN,"{""link"":"""",""source"":""""}","{""id"":""100682070858728287973"",""name"":""Park \""L...","{""borough"":"""",""street"":""Poselok Sovkhoz Imeni ...",NaN,[],"[{""Name"":""shulc666"",""ProfilePicture"":""https://...",NaN,amusement_parks_trampoline_centers.json,"park ""lukomor'ye""_poselok sovkhoz imeni lenina..."
4,837aed36-07fb-4804-85b2-be8e0285a3b1,https://www.google.com/maps/place/Sportivno-Ra...,Sportivno-Razvlekatel'nyy Tsentr Nebo Krymskaya,Amusement center,"Sevastopolskiy Ave, 11Е, 3 Etazh, Tts Kapitoli...","{""Friday"":[""10 AM–10 PM""],""Monday"":[""10 AM–10 ...","{""Friday"":{""10"":25,""11"":40,""12"":56,""13"":66,""14...",http://nebojump.ru/,+7 495 172-11-32,"MJP3+XJ Kotlovka District, Moscow, Russia",982,4.7,"{""1"":32,""2"":14,""3"":19,""4"":119,""5"":798}",55.687413,37.604036,1639074325311235891,Closes soon ⋅ 10 PM ⋅ Opens 10 AM Wed,NaN,https://search.google.com/local/reviews?placei...,https://lh3.googleusercontent.com/p/AF1QipM5nq...,Europe/Moscow,NaN,0x46b54caf4620ecf7:0x16bf296a28a3a733,"[{""title"":""All"",""image"":""https://lh3.googleuse...",NaN,NaN,"{""link"":"""",""source"":""""}","{""id"":""109359907457198669995"",""name"":""Sportivn...","{""borough"":""South-Western Administrative Okrug...","[{""id"":""accessibility"",""name"":""Accessibility"",...",[],"[{""Name"":""Наталья А."",""ProfilePicture"":""https:...",NaN,amusement_parks_trampoline_centers.json,sportivno-razvlekatel'nyy tsentr nebo krymskay...

Удаление дубликатов

In [35]:
def remove_duplicates(df):
    df['unique_key'] = (
        df['title'].str.lower() + '_' +
        df['address'].str.lower() + '_' +
        df['latitude'].astype(str) + '_' +
        df['longitude'].astype(str)
    )
    df = df.sort_values(by=['unique_key', 'review_count'], ascending=[True, False])
    df = df.drop_duplicates(subset='unique_key', keep='first')  # С max отзывами для рекомендаций
    df = df.drop(columns=['unique_key'])
    print(f"После удаления дубликатов: {len(df)} строк")
    return df

In [36]:
df_clean = remove_duplicates(df)

После удаления дубликатов: 3157 строк

Анализ столбцов

In [41]:
df_clean.isna().sum()

input_id                    0
link                        0
title                       0
category                    8
address                     1
open_hours                  0
popular_times               0
website                  1012
phone                     518
plus_code                  13
review_count                0
review_rating               0
reviews_per_rating          0
latitude                    0
longitude                   0
cid                         0
status                    677
descriptions             2899
reviews_link              143
thumbnail                  68
timezone                    0
price_range              2560
data_id                     0
images                      0
reservations             2960
order_online             2827
menu                        0
owner                       0
complete_address            0
about                     302
user_reviews                0
user_reviews_extended     621
emails                   3157
original_file               0
dtype: int64

In [56]:
df_clean.columns

Index(['input_id', 'link', 'title', 'category', 'address', 'open_hours',
       'popular_times', 'website', 'phone', 'plus_code', 'review_count',
       'review_rating', 'reviews_per_rating', 'latitude', 'longitude', 'cid',
       'status', 'descriptions', 'reviews_link', 'thumbnail', 'timezone',
       'price_range', 'data_id', 'images', 'reservations', 'order_online',
       'menu', 'owner', 'complete_address', 'about', 'user_reviews',
       'user_reviews_extended', 'emails', 'original_file'],
      dtype='object')

In [61]:
df_clean['about'][0]

'[{"id":"accessibility","name":"Accessibility","options":[{"name":"Wheelchair accessible entrance","enabled":true},{"name":"Wheelchair accessible parking lot","enabled":true},{"name":"Wheelchair accessible restroom","enabled":true},{"name":"Wheelchair accessible seating","enabled":true}]},{"id":"amenities","name":"Amenities","options":[{"name":"Swimming pool","enabled":false}]},{"id":"crowd","name":"Crowd","options":[{"name":"LGBTQ+ friendly","enabled":true},{"name":"Transgender safespace","enabled":true}]},{"id":"payments","name":"Payments","options":[{"name":"Credit cards","enabled":true},{"name":"Debit cards","enabled":true},{"name":"NFC mobile payments","enabled":true},{"name":"Credit cards","enabled":false}]},{"id":"children","name":"Children","options":[{"name":"Good for kids birthday","enabled":true},{"name":"Kid-friendly activities","enabled":true}]}]'

In [62]:
df_clean['user_reviews_extended'][0]

'[{"Name":"Jordan Lott","ProfilePicture":"https://lh3.googleusercontent.com/a-/ALV-UjV2Fa1LEhVUE55ow79jlqCinFmje0G0wwnzRolYCi-u5s0SbrmN=s120-c-rp-mo-ba2-br100","Rating":3,"Description":"I learned that as a flying squirrel brand they are the largest. You should be aware tough that this building is one of their smaller buildings. Still lots of fun activities. Aside from the size, the prices were ridiculous. 20per hour? There doesn\'t seem to be much else to do in these small towns so idk how much I cant fault them for being smart at business. Supply and demand at its finest. Lastly, the rules are tighter than other parks I\'ve been to.. some may really appreciate this, I get it. I did not.( I am a live and let live, accept the risk kindness person) My review is based on personal preference and experiences elsewhere. Positives are clean environment. I had little to no interaction with staff so I can\'t judge that.  If I hadn\'t been to any other park it would be expensive but fun... I wish they wouldn\'t charge by the hr..it makes you feel rushed when you are reminded about the limited time you have by a bracelet with a countdown timer... lame corporate involvement I\'m sure. The owner is very nice and kind and involved.  The place is fun and and would recommend for short quick fun.","Images":null,"When":""},{"Name":"Jacques Bouchard","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocLpEDPbXGfNArQw3fe9y_Ri3gkp3i6X8bqqFiEg3D-P30FU_g=s120-c-rp-mo-br100","Rating":5,"Description":"Had a great time. Had to change birthday venue abruptly due to AQI issues we called and 30 minutes later our birthday plans were saved. Professional service. What a great place to have a birthday party!","Images":null,"When":""},{"Name":"Addie Callihan","ProfilePicture":"https://lh3.googleusercontent.com/a-/ALV-UjX49XvTIHMzIc01fRsJudhkQOIZ1K69ItveXh2aq5um45IGwdmz=s120-c-rp-mo-br100","Rating":4,"Description":"Such a great place to bring the kids! Lots of different things to do, never crowded, fairly priced. 👌","Images":["www.google.com/local/imagery/report/?cb_client=maps_sv.tactile\\u0026image_key=!1e10!2sCIABIhBA5Y36SbiIX00aiolFuov0\\u0026fid=0x0:0xbdfe0ec9ca8edcfa"],"When":"2025-9-9"},{"Name":"Katie Beggs","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocLsePso8oELfp6n311sQHeA_cRc1RkIl6n7Kbeu_QkL3QGZqw=s120-c-rp-mo-ba3-br100","Rating":5,"Description":"I had to book a birthday party last minute, literally an hour before we went. The person I talked to on the phone was great! He was super accommodating and was able to get some strings pulled and get us a table and pizzas for the party. Upon arriving they were all very helpful and made our experience a great one!","Images":["www.google.com/local/imagery/report/?cb_client=maps_sv.tactile\\u0026image_key=!1e10!2sCIHM0ogKEICAgIDVsrjGbA\\u0026fid=0x0:0xbdfe0ec9ca8edcfa"],"When":"2023-12-12"},{"Name":"Laura Pugh","ProfilePicture":"https://lh3.googleusercontent.com/a-/ALV-UjWQ6SVRQ7Ei8kgToBFf42HmGUxUt9oDplHSbQnblPzWNVsW3LLL=s120-c-rp-mo-ba4-br100","Rating":5,"Description":"Great indoor activity for kids and adults. Neon night was extra fun. Not too crowded when we went on a Sunday evening. Bring your own trampoline socks! We didn\'t play any arcade games because my kids just wanted to jump the whole time, but there\'s a good selection.","Images":null,"When":""},{"Name":"jeanette brooks","ProfilePicture":"https://lh3.googleusercontent.com/a-/ALV-UjWU7iSGdJxd4IKrvzpEPizU_ULmmucKj3vziyeSnV1RROyxxYoB=s120-c-rp-mo-ba2-br100","Rating":4,"Description":"My only issue is the massage chairs. You must pay to sit in them, and the massage was very rough, as I left the chair before my paid time had expired. My kid had a blast, though, and that\'s really all that matters.","Images":null,"When":""},{"Name":"L j","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocKYJ5FkqxGIo8Bw97NdDbXDRIym-mMvMAx-YClc5QV_9BX05Q=s120-c-rp-mo-ba3-br100","Rating":5,"Description":"I take my grandkids here about once a month, and they absolutely love it. I appreciate how easy the check-in process is. Many of the staff remember the kids\' names and are checking them in before I even get to the counter, which is fabulous, especially considering the age group of the staff. Birthday parties here are very fun and easy here as well, once again, thanks to the amazing group of staff. Outstanding all the way around!!!","Images":null,"When":""},{"Name":"Kelcey Evans","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocJPcllQqeIB236DWOWPIRfQkQ3W755r8ctpLpURFX0GPINcAw=s120-c-rp-mo-br100","Rating":3,"Description":"Went there for a birthday party yesterday 3/21. Jumping was fun and toddler friendly. Customer service was not friendly.\\n\\nManager yelled in my toddlers face for other kids to stop screaming. My son has sensitive hearing so it hurt his ears.\\n\\nA little kid throw up and my daughter almost stepped in it because the employee just stood behind the soda rack instead of blocking the area.  The mother was trying to help her child while another parent went and got papers towels. The employee started to help clean up when they got back. I don\'t know what they protocol is for when a child gets sick but seemed stressful and not handled well.\\n\\nSigning in was stressful because tablet wasn\'t working and employee wasn\'t helpful. They told me to start over on another tablet took my 5 trys filling the whole thing out before it worked. I understand it needs to be filled out but when your having internet problems maybe have a paper option.","Images":null,"When":""},{"Name":"Elizabeth Taylor","ProfilePicture":"https://lh3.googleusercontent.com/a-/ALV-UjXScsEKLlL0EFrVu_ec2vprdLErx7E8TmrnOzDT9JbsDW6P8FLuqw=s120-c-rp-mo-ba4-br100","Rating":4,"Description":"A really neat place! It was a good birthday location, I just wish there was privacy between parties. They give each party a table, not like a separate room.","Images":null,"When":""},{"Name":"Vanessa Sturing","ProfilePicture":"https://lh3.googleusercontent.com/a-/ALV-UjVg9BMtLB7QBgATIfcWfLiqoWUVwWi5PCoFsKaPMJ-RUmFMneY=s120-c-rp-mo-br100","Rating":5,"Description":"The best place for kids and adults to get their wiggles out! And if sitting down watching your kid is more your speed you can enjoy a nice massage chair for a few dollars and still have a visual on your kid because as many different cool areas this park has you can easily keep your eyes on your kids from their chairs and benches around the park. Amelia who works there can show you how to make the chairs work in case you aren’t good with electronics like me.\\nBrandon who works there is not only handsome but great with his little siblings when they go see big brother at work, it makes my mom heart proud to see how kind he is to other peoples children and helpful when I get to watch him in his workplace.\\nThey have a very caring team that works hard to create a safe and fun environment for all ages.\\nThey even decorate for the seasons which I love because I’m a festive type, and the kids really enjoy it too!","Images":null,"When":""},{"Name":"James Bramell","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocIFEMxgDm9Ipm2TiEzOUAKQREAKzUL8qpFLaYDKS3sCSyPgNg=s120-c-rp-mo-ba6-br100","Rating":5,"Description":"Great customer service and amazing fun for kids. Military discount and a good process to get on the trampoline floor. Plenty of room and chairs for non jumpers. An arcade and party area with lots of space, vending machines and more. A great place for kids to play!","Images":["www.google.com/local/imagery/report/?cb_client=maps_sv.tactile\\u0026image_key=!1e10!2sCIHM0ogKEICAgICppNLA0wE\\u0026fid=0x0:0xbdfe0ec9ca8edcfa"],"When":"2023-7-28"},{"Name":"Monkey Boy","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocLhoghV7oG11kxi12ohZG9KKhl2wPuIV5nqyBfNOziLMEYD3w=s120-c-rp-mo-br100","Rating":5,"Description":"I absolutely loved it here and my brothers loved it as well. This is definitely one of my favorite places to visit, the arcade games were super fun.","Images":null,"When":""},{"Name":"Richard Castro","ProfilePicture":"https://lh3.googleusercontent.com/a-/ALV-UjV5c2IPaYUdfE9nGhmY27dymP_aCrCPnEmWf7ATM3JHPm2kiksk=s120-c-rp-mo-ba4-br100","Rating":5,"Description":"23 and 21 yr olds. Trampolines make you very tired. The workers were friendly and relaxed. This place isn\'t just Trampolines. We liked the basketball Trampoline a lot. I liked the beam where you fight someone but she didn\'t like losing. The foam pits are very soft so you\'ll be fine if you fall. There is a dodge ball, rock climbing, swing, and arcade section too. You don\'t have to be kid to like it here.","Images":["www.google.com/local/imagery/report/?cb_client=maps_sv.tactile\\u0026image_key=!1e10!2sCIHM0ogKEICAgIDJz66XGQ\\u0026fid=0x0:0xbdfe0ec9ca8edcfa"],"When":"2023-7-25"},{"Name":"Staci Smith","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocJmSyKuGF9b1IpYPtN5R_Q8a2jsCV4WwYQdhe2FOg9zumWisg=s120-c-rp-mo-br100","Rating":5,"Description":"Amazing place! Well worth the hour drive for us! Kids enjoy it and were surprised to see the lights dim on Friday evening! They can jump off some energy, play some basketball, and parents can sit in massage chairs and relax! ☆☆☆☆☆","Images":["www.google.com/local/imagery/report/?cb_client=maps_sv.tactile\\u0026image_key=!1e10!2sCIHM0ogKEICAgIDN8MeqWw\\u0026fid=0x0:0xbdfe0ec9ca8edcfa"],"When":"2024-1-20"},{"Name":"Dr. Cass Hedrick, DACM, LAc","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocLYZu6ThiCpQvHtqtPeEYIIWUm0V7hCsvvAXVna8SLi-0gCpQ=s120-c-rp-mo-br100","Rating":5,"Description":"Took my 2 yr old son to burn some energy on a hot day. He LOVED IT! And he slept harrrrd that night. Worth. Every. Penny.","Images":null,"When":""},{"Name":"D Whiteley","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocI0QoXVBE-oMENQV0zKHZAh4o2a1uXWInUfmfXP1g8x3YZCsw=s120-c-rp-mo-ba3-br100","Rating":3,"Description":"I took 3 kids to the Flying Squirrel on a Friday evening. I gave 3 stars because of the unbelievably high price. It cost a couple of dollars under $60 for 1 hour of jump time for the 3 kids. There are so few activities for kids in the area that it\'s sad to know that most people that live here can\'t afford to pay that kind of money to take their kids to an indoor activity like this. Ok, so to move on from the cost, I could have missed seeing the employees, but it seemed like a very low staff to jumper ratio. I saw 1 employee checking people in and one employee at the actual jumping  area. It wasn\'t as crowded as I have seen in the past but there were at least 25 people there. The few staff were polite, the valve was fairly clean including the ladies bathroom. They do not heat the bathroom so be prepared to feel like your using an out house in the winter.","Images":null,"When":""},{"Name":"Mohammad Al Ebedan","ProfilePicture":"https://lh3.googleusercontent.com/a-/ALV-UjUvgYbsyWYsARhHATkfHie_X3zyxsU-ez0AEDYePjrqrGWas3HS=s120-c-rp-mo-ba3-br100","Rating":4,"Description":"All ages can enjoy their time here. It’s really great jumping, climbing area. Let’s of things to do here don’t miss it! Some people are saying their price is a little high in the area like Moscow!","Images":["www.google.com/local/imagery/report/?cb_client=maps_sv.tactile\\u0026image_key=!1e10!2sCIHM0ogKEICAgIDN0ZO94QE\\u0026fid=0x0:0xbdfe0ec9ca8edcfa"],"When":"2024-1-23"},{"Name":"Kiley Johnson","ProfilePicture":"https://lh3.googleusercontent.com/a-/ALV-UjU5TN5irvlM1sLX42njzR2Xg2gYFj1KdwJAKj7B0aZiowTZHFL2UA=s120-c-rp-mo-ba5-br100","Rating":5,"Description":"Always a super fun place! They have decent group discounts and discounts for kids with dd which is super amazing of them! The place is always clean and the staff friendly! Great place to take kids, groups, or even anyone that likes to jump. We went over spring break which was more busy than usual but the middle of the day is usually very busy!","Images":null,"When":""},{"Name":"Erin Reece","ProfilePicture":"https://lh3.googleusercontent.com/a-/ALV-UjWX3m1bbxeGX7dGUIXLO_8riK-8HWA2KNvvPZIMdetgHEd_n3k=s120-c-rp-mo-br100","Rating":5,"Description":"We moved from the area 2 years ago and just got back. My kids have been begging to go back. We got there and it did change a lot (new branding?) Ian at the front desk was very professional and even remembered that one of my sons used to request Eye of the Tiger to be played 2 years ago! Ian was very helpful walking us through the changes and making sure we felt right at home. The staff was very courteous and helpful at all the stations. All the kids cant wait to go back!","Images":null,"When":""},{"Name":"Caleb Smith","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocKRlzYlCMLu9gPgvW7HvYqIdBldzpIqBG2VO0bFETJgKjH_yQ=s120-c-rp-mo-br100","Rating":1,"Description":"We purchased jump passes for our nieces last Christmas and tried to use them this year on December 27th. The passes did not say they expire on them and the email containing the passes did not say that they expire. So if you are the recipient of the passes and not the purchaser you would have no idea that could even expire. It also did not say in bold letters at the time of purchase that this was the case. The concept of passes expiring is a scam in the first place, the business already received the money and we still had the passes in hand. I would love to hear a logical explanation as to how letting customers hold a pass for longer than a year negatively impacts the business. The guy behind the counter was not friendly in the slightest and the lady who appeared to be the manager was rude. I also witnessed her being rude to other patrons. It’s one thing to have a policy that allows the business to take money in exchange for nothing, it’s another to be rude to people who are just trying to understand why you would have such a policy in the first place.","Images":null,"When":""},{"Name":"Gabriel Rodriguez","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocIIvmoZhQWRbM4ugkZVhzK9TGb4GTVWIukhe2LRkiqR6V-CUg=s120-c-rp-mo-ba3-br100","Rating":1,"Description":"Was given a gift certificate to use last Christmas (we\'re from out of town, 8 hours away), came to use it today and they refuse to take it (they say it expired 2 weeks ago, but no expiration on our certificate). I would not buy gift certificates from this place, they pocketed the money for the gift certificate and we paid full price to enter. Please honor your gift certificates as money was paid and not used.","Images":null,"When":""},{"Name":"Em Ar","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocK82t6U8gc9qMoqbBAXwZ8NhCdt5ovDhTZt4dLgzv1qgqAK=s120-c-rp-mo-br100","Rating":2,"Description":"This is a fun place to take the kids, But the staff needs to be more attentive. I understand they’re young but they have terrible work ethic. If they don’t look upset to be there then they’re too busy gossiping to one another to pay attention to their jobs. They roll their eyes at the kids and make unnecessary remarks under their breath.\\nTwo of the boys working at the time just wanted to converse instead of doing their jobs. They were supposed to be working at the swing but instead couldn’t be bothered to even stand when doing this task. One was sitting and lazily catching the pole and letting it go before kids were even able to grab on. When confronted about it, they just went silent, looked at each other and  continued their conversation without any humility about their poor attention and work.\\nYou would think going on a slow day would have better service, but it’s been poor service each time we’ve visited.\\nUnfortunately there’s not much else to do in this town for kids because this establishment doesn’t deserve the business they get.","Images":null,"When":""},{"Name":"Jennifer Simler","ProfilePicture":"https://lh3.googleusercontent.com/a-/ALV-UjWiGt7wMHzNFZYBOO2Yytz6BkcVdhm16zcUcijTzvnveTaYened=s120-c-rp-mo-ba2-br100","Rating":5,"Description":"Fun for all ages! We like to go in the winter when it’s too cold to take our kiddos outside. It’s a great way to burn off energy! It’s nice that there is a “jungle gym” with a foam pit and not just trampolines.","Images":null,"When":""},{"Name":"AMANDA","ProfilePicture":"https://lh3.googleusercontent.com/a-/ALV-UjUk-DcJLoHuJk4HcoKVA04gYEBxqvJ8cuix6Ve7kbh3v33jNPuf=s120-c-rp-mo-br100","Rating":5,"Description":"The staff here get it!\\n\\nIt is a great place to bring the herd of humans to run and play in a confined and safe place.\\n\\nLots of fun.","Images":null,"When":""},{"Name":"Matthew Prescott","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocJywA8OCr41wL6Q0VZErzjAr9_9M2BP42mwXzDiNGPfHKx111I=s120-c-rp-mo-br100","Rating":1,"Description":"Review from a Christian, which is only important to note because my main issue was a moral one. I stopped in here with my young daughter in the hopes that we might have a nice and active day of trampoline bouncing. The theme/decor on the outside was innocent enough, with artsy renditions of cute little squirrels plastered around. However, upon entering the building, I was pretty dismayed to find, for reasons I can\'t completely understand, several fake gargoyle-like statues representing what appeared to be Satan in both the area where you sign the the liability waiver as well as in the area where you store your shoes. It is the end of January, and nowhere near Halloween, although that would still be pretty tacky even if it were in \\"season,\\" in my opinion. That combined with the use of purple string lights left me wondering...was the owner just a proud pagan? Do they just have terrible design sensibilities? Is this an attempt to just be edgy and attract an older teenage crowd? Ultimately it didn\'t matter, but that is a very poor choice of decor for a facility that supposedly welcomes younger bouncers, and someone - anyone - really should have known that. I drove over an hour for what I hoped would be a memorable day, and instead was blindsided by dark energy and bad vibes. In a day in age where putting multiple Crosses up in these same spaces would raise eyebrows, I don\'t know why the bad guy from Fantasia passes for normal and acceptable. I still can\'t figure it out... it was totally weird.\\n\\nIn any case, a secondary but more practical concern was that, when there is a birthday (as there was on this particular day), the facility doesn\'t appear to be large enough to bounce safely. The number of kids was overwhelming, and people were on top of each other. We might have just caught it at a bad time, but still. This was not a good experience and ultimately was a waste of my time. I certainly couldn\'t come back to try it again until someone with better interior design (or perhaps more awareness and empathy) makes the space more age appropriate.\\n\\nMaybe just stick to the cute flying squirrels....?","Images":null,"When":""},{"Name":"Kelsey McAuliffe","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocKCqhV_FO6eqLK1LCEQstwm3BrQSFxJdP4w5e69fzPjAZKNUA=s120-c-rp-mo-ba2-br100","Rating":5,"Description":"They were really great about moving around a birthday party. Fun jumping.","Images":null,"When":""},{"Name":"Michelle Hazen","ProfilePicture":"https://lh3.googleusercontent.com/a-/ALV-UjUMXMMX-e-FKbs5k3Kg9qQmr-6pB2zKqRDHDVv3B_6-c7lU5HU=s120-c-rp-mo-ba4-br100","Rating":5,"Description":"My 9 year old requested I rate this 5 stars! She loves it and it\'s a great indoor space to get some energy out on cold and rainy or snowy days. She loves the arcade too, but it\'s classic arcade- pricy video games and games to win prizes that are near impossible to win. Overall fun place.","Images":null,"When":""},{"Name":"Sarah Graham","ProfilePicture":"https://lh3.googleusercontent.com/a/ACg8ocJRnPY6sBrjZ594opf0WYZTYw-1uiJLaRBcb8x8hzU_FG7rqA=s120-c-rp-mo-br100","Rating":5,"Description":"We\'ve been to a lot of trampoline parks.  But this one impressed me.  Usually the staff members seem annoyed by kids but the

Удаление очевидно ненужных столбцов

In [64]:
df_clean['user_reviews'].value_counts()

user_reviews
[]    3157
Name: count, dtype: int64

In [67]:
# emails - полностью пустой
# user_reviews - содержит пустые списки
df_clean = df_clean.drop(['emails', 'user_reviews'], axis=1)

In [68]:
df_clean.columns

Index(['input_id', 'link', 'title', 'category', 'address', 'open_hours',
       'popular_times', 'website', 'phone', 'plus_code', 'review_count',
       'review_rating', 'reviews_per_rating', 'latitude', 'longitude', 'cid',
       'status', 'descriptions', 'reviews_link', 'thumbnail', 'timezone',
       'price_range', 'data_id', 'images', 'reservations', 'order_online',
       'menu', 'owner', 'complete_address', 'about', 'user_reviews_extended',
       'original_file'],
      dtype='object')

Создание таблицы с отзывами пользователей

In [ ]:
# Добавим в основную таблицу простые id
df_clean['place_id'] = range(len(df_clean))

In [72]:
# Список для сборки отзывов
reviews_list = []
for idx, row in df_clean.iterrows():
    place_id = row['place_id']
    reviews_str = row['user_reviews_extended']
    if pd.notna(reviews_str) and reviews_str.strip():  # Проверяем на пустоту
        try:
            reviews = json.loads(reviews_str)  # Парсим JSON
            for review in reviews:
                review['place_id'] = place_id  # Добавляем place_id к каждому отзыву
                reviews_list.append(review)
        except json.JSONDecodeError as e:
            print(f"Ошибка парсинга JSON для place_id {place_id}: {e}")  # Логируем ошибки

In [73]:
# Создаем новый DataFrame
user_reviews_data = pd.DataFrame(reviews_list)

In [74]:
user_reviews_data.head()

,Name,ProfilePicture,Rating,Description,Images,When,place_id
0,Andreas Pantelis Moursellas,https://lh3.googleusercontent.com/a-/ALV-UjVmG...,5,Εντυπωσιακό μουσείο με εκθέματα από το διαστημ...,None,,1
1,Krasen Hristov,https://lh3.googleusercontent.com/a/ACg8ocKkGG...,5,Very rich and beautiful exhibition of the USSR...,[www.google.com/local/imagery/report/?cb_clien...,2025-9-20,1
2,Antonius,https://lh3.googleusercontent.com/a-/ALV-UjVx5...,5,Павильон был построен в 1938—1939 годах и носи...,[www.google.com/local/imagery/report/?cb_clien...,2024-11-23,1
3,Bulushova Lidiya,https://lh3.googleusercontent.com/a-/ALV-UjVvI...,4,"Как музей весьма средне, а как место, где можн...",[www.google.com/local/imagery/report/?cb_clien...,2025-3-10,1
4,Максим,https://lh3.googleusercontent.com/a-/ALV-UjW4D...,5,Абсолютно стоит потраченных денег. Очень много...,[www.google.com/local/imagery/report/?cb_clien...,2025-4-10,1

In [75]:
user_reviews_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1547630 entries, 0 to 1547629
Data columns (total 7 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   Name            1547630 non-null  object
 1   ProfilePicture  1547630 non-null  object
 2   Rating          1547630 non-null  int64
 3   Description     1547630 non-null  object
 4   Images          224080 non-null   object
 5   When            1547630 non-null  object
 6   place_id        1547630 non-null  int64
dtypes: int64(2), object(5)
memory usage: 82.7+ MB

In [ ]:
# Удалим ProfilePicture и Images
user_reviews_data = user_reviews_data.drop(['ProfilePicture', 'Images'], axis=1)

In [80]:
# Сохраняем файл
user_reviews_data.to_csv('user_reviews_data.csv', index=False)

Добавление фичей из столбца about

In [81]:
df_clean['about'].isna().sum()

np.int64(302)

In [83]:
# Функция для парсинка json из строк
def safe_parse_json(json_str):
    if pd.isna(json_str) or not isinstance(json_str, str) or json_str.strip() == '':
        return None
    try:
        return json.loads(json_str)
    except json.JSONDecodeError as e:
        print(f"Ошибка парсинга JSON в столбце 'about': {e}")
        return None

In [84]:
# Собираем все уникальные имена опций из столбца 'about'
unique_options = set()
for about_str in df_clean['about']:
    about_data = safe_parse_json(about_str)
    if about_data:
        for category in about_data:
            options = category.get('options', [])
            for option in options:
                option_name = option.get('name', '')
                if option_name:
                    # Преобразуем имя опции в безопасное для столбца (заменяем пробелы на подчеркивания, убираем спецсимволы)
                    safe_name = option_name.lower().replace(' ', '_').replace('+', '_plus').replace('-', '_')
                    unique_options.add(safe_name)

In [85]:
# Функция для извлечения фич для одной строки
def extract_about_features(row):
    about_data = safe_parse_json(row['about'])
    # Инициализируем словарь с np.nan для всех возможных опций
    features = {option: np.nan for option in unique_options}
    
    if about_data:
        for category in about_data:
            options = category.get('options', [])
            for option in options:
                option_name = option.get('name', '')
                if option_name:
                    safe_name = option_name.lower().replace(' ', '_').replace('+', '_plus').replace('-', '_')
                    features[safe_name] = option.get('enabled', False)
    
    return pd.Series(features)

In [86]:
# Применяем функцию и добавляем новые столбцы в df_clean
about_features = df_clean.apply(extract_about_features, axis=1)
df_clean = pd.concat([df_clean, about_features], axis=1)

In [98]:
df_clean.wi_fi.isna().sum()

np.int64(2662)

In [91]:
print(f"Добавлены динамические столбцы: {list(unique_options)}")
print(f"Форма df_clean после добавления фич: {df_clean.shape}")
print("Первые 2 строки с новыми фичами (показаны только первые 5 новых столбцов):")
new_columns = list(unique_options)[:5]  # Показываем только первые 5 для примера
print(df_clean[['place_id'] + new_columns].head(2))

Добавлены динамические столбцы: ['skincare_treatments', 'dogs_allowed_inside', 'picnic_tables', 'has_changing_table(s)', 'dancing', 'family_friendly', 'transgender_safespace', 'comfort_food', 'brunch_reservations_recommended', 'food_at_bar', 'great_wine_list', 'brunch', 'organic_dishes', 'catering', 'wheelchair_accessible_restroom', 'vegetarian_options', 'counter_service', 'small_plates', 'late_night_food', "kids'_menu", 'great_tea_selection', 'debit_cards', 'great_coffee', 'credit_cards', 'online_classes', 'live_music', 'public_restroom', 'good_for_working_on_laptop', 'assisted_listening_devices', 'kid_friendly_hikes', 'petting_zoo', 'all_you_can_eat', 'usually_a_wait', 'playground', 'party_services', 'fast_service', 'cash_only', 'paid_parking_garage', 'swimming_pool', 'dine_in', 'outdoor_seating', 'healthy_options', 'cafe', 'great_produce', 'beer', 'trivia_night', 'quick_bite', 'restaurant', 'appointment_required', 'delivery', "men's_clothing", 'food', 'hard_liquor', 'valet_parking', 'seating', 'kid_friendly_activities', 'swings', 'dessert', 'checks', 'parking', 'lgbtq_plus_friendly', 'lively', 'in_store_pickup', 'dinner', 'cozy', 'wi_fi', 'family_discount', 'live_performances', 'quiet', 'bar_games', 'cocktails', 'happy_hour_food', 'good_for_kids_birthday', 'membership_required', 'bar_onsite', 'cycling_lanes', 'takeout', 'great_dessert', 'college_students', 'salad_bar', 'discounts_for_kids', 'table_service', 'great_beer_selection', 'locals', 'reservations_required', 'paid_parking_lot', 'great_bar_food', 'upscale', 'free_parking_garage', 'onsite_services', 'alcohol', 'wheelchair_accessible_parking_lot', 'vegan_options', 'arcade_games', 'outside_food_allowed', 'online_scheduling', 'organic_products', 'breakfast', 'solo_dining', 'happy_hour_drinks', 'lunch', 'trendy', 'baggage_storage', 'hiking', 'romantic', 'wine', 'nfc_mobile_payments', 'great_cocktails', 'identifies_as_women_owned', 'accepts_reservations', 'karaoke', 'dinner_reservations_recommended', '3d_movies', 'historic', 'gift_shop', 'offers_tours', 'stadium_seating', 'sports', 'fireplace', 'drive_through', '24_hour_transit_available', 'clothing', 'good_for_kids', 'quick_visit', 'slides', 'wheelchair_accessible_seating', 'passport_photos', 'outdoor_services', 'sauna', 'skateboarding_area', 'dogs_allowed_outside', 'basketball_court', 'picnics', 'wheelchair_rental', 'paid_street_parking', 'getting_tickets_in_advance_recommended', 'free_street_parking', 'tourists', 'restroom', 'halal_food', 'online_appointments', 'in_store_shopping', 'coffee', 'assistive_hearing_loop', 'on_site_parking', 'has_a_tennis_court', 'appointments_recommended', 'groups', 'no_contact_delivery', 'dog_park', 'casual', 'trending', 'private_dining_room', 'volleyball_court', 'child_care', 'prepared_foods', 'gender_neutral_restroom', 'rooftop_seating', 'dogs_allowed', 'braille_menu', 'lunch_reservations_recommended', 'wheelchair_accessible_entrance', 'high_chairs', 'membership', 'free_parking_lot']
Форма df_clean после добавления фич: (3157, 198)
Первые 2 строки с новыми фичами (показаны только первые 5 новых столбцов):
      place_id skincare_treatments dogs_allowed_inside picnic_tables  \
326          0                 NaN                 NaN           NaN
2977         1                 NaN                 NaN           NaN

     has_changing_table(s) dancing
326                    NaN     NaN
2977                   NaN     NaN

In [97]:
unique_options

{'24_hour_transit_available',
 '3d_movies',
 'accepts_reservations',
 'alcohol',
 'all_you_can_eat',
 'appointment_required',
 'appointments_recommended',
 'arcade_games',
 'assisted_listening_devices',
 'assistive_hearing_loop',
 'baggage_storage',
 'bar_games',
 'bar_onsite',
 'basketball_court',
 'beer',
 'braille_menu',
 'breakfast',
 'brunch',
 'brunch_reservations_recommended',
 'cafe',
 'cash_only',
 'casual',
 'catering',
 'checks',
 'child_care',
 'clothing',
 'cocktails',
 'coffee',
 'college_students',
 'comfort_food',
 'counter_service',
 'cozy',
 'credit_cards',
 'cycling_lanes',
 'dancing',
 'debit_cards',
 'delivery',
 'dessert',
 'dine_in',
 'dinner',
 'dinner_reservations_recommended',
 'discounts_for_kids',
 'dog_park',
 'dogs_allowed',
 'dogs_allowed_inside',
 'dogs_allowed_outside',
 'drive_through',
 'family_discount',
 'family_friendly',
 'fast_service',
 'fireplace',
 'food',
 'food_at_bar',
 'free_parking_garage',
 'free_parking_lot',
 'free_street_parking',
 'gender_neutral_restroom',
 'getting_tickets_in_advance_recommended',
 'gift_shop',
 'good_for_kids',
 'good_for_kids_birthday',
 'good_for_working_on_laptop',
 'great_bar_food',
 'great_beer_selection',
 'great_cocktails',
 'great_coffee',
 'great_dessert',
 'great_produce',
 'great_tea_selection',
 'great_wine_list',
 'groups',
 'halal_food',
 'happy_hour_drinks',
 'happy_hour_food',
 'hard_liquor',
 'has_a_tennis_court',
 'has_changing_table(s)',
 'healthy_options',
 'high_chairs',
 'hiking',
 'historic',
 'identifies_as_women_owned',
 'in_store_pickup',
 'in_store_shopping',
 'karaoke',
 'kid_friendly_activities',
 'kid_friendly_hikes',
 "kids'_menu",
 'late_night_food',
 'lgbtq_plus_friendly',
 'live_music',
 'live_performances',
 'lively',
 'locals',
 'lunch',
 'lunch_reservations_recommended',
 'membership',
 'membership_required',
 "men's_clothing",
 'nfc_mobile_payments',
 'no_contact_delivery',
 'offers_tours',
 'on_site_parking',
 'online_appointments',
 'online_classes',
 'online_scheduling',
 'onsite_services',
 'organic_dishes',
 'organic_products',
 'outdoor_seating',
 'outdoor_services',
 'outside_food_allowed',
 'paid_parking_garage',
 'paid_parking_lot',
 'paid_street_parking',
 'parking',
 'party_services',
 'passport_photos',
 'petting_zoo',
 'picnic_tables',
 'picnics',
 'playground',
 'prepared_foods',
 'private_dining_room',
 'public_restroom',
 'quick_bite',
 'quick_visit',
 'quiet',
 'reservations_required',
 'restaurant',
 'restroom',
 'romantic',
 'rooftop_seating',
 'salad_bar',
 'sauna',
 'seating',
 'skateboarding_area',
 'skincare_treatments',
 'slides',
 'small_plates',
 'solo_dining',
 'sports',
 'stadium_seating',
 'swimming_pool',
 'swings',
 'table_service',
 'takeout',
 'tourists',
 'transgender_safespace',
 'trending',
 'trendy',
 'trivia_night',
 'upscale',
 'usually_a_wait',
 'valet_parking',
 'vegan_options',
 'vegetarian_options',
 'volleyball_court',
 'wheelchair_accessible_entrance',
 'wheelchair_accessible_parking_lot',
 'wheelchair_accessible_restroom',
 'wheelchair_accessible_seating',
 'wheelchair_rental',
 'wi_fi',
 'wine'}

In [99]:
# Сохраняем файл
df_clean.to_csv('df_clean.csv', index=False)